apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x5yl3jtw7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x5yl3jtw7-python 
  name: x5yl3jtw7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x5yl3jtw7-python 
